#if !canImport(ObjectiveC)
import XCTest

extension Connect {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Connect = [
        ("testConnect", testConnect),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Connect.__allTests__Connect),
    ]
}
#endif
