#if !canImport(ObjectiveC)
import XCTest

extension MyTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MyTest = [
        ("testConnect", testConnect),
        ("testJoinGroup", testJoinGroup),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MyTest.__allTests__MyTest),
    ]
}
#endif
