name: "Publish Documentation"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1.3.0
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install jazzy
      run: sudo gem install jazzy
    - name: Generate docs
      run: jazzy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
