name: "Publish Documentation"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [  main  ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: tbartelmess/setup-swift@v1.5.0
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Ruby
      run: sudo apt install ruby ruby-devel
    - name: Install jazzy
      run: sudo gem install jazzy
    - name: Generate docs
      run: jazzy
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
