name: test-on-linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [  main  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fwal/setup-swift@v1
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Show Swift Version
      run: swift --version
    - name: Build
      run: swift build
    - name: Test
      run: swift test
