name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [  main  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: fwal/setup-swift@v1
    - name: Build
      run: swift build
    - name: Test
      run: swift test
